### ISSUE TITLE
Move from TSD to Typings

### ISSUE THREAD

**Issue by tdbrian** [KarlPurk/redux-decorators#14]
TSD to Typings which is recommended now by the TSD author. 

> DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information.

See PR #12 for change

**Comment by tdbrian** [comment]
Just saw this has already been done in the develop branch. I'll go ahead and remove my PR and re-add other changes to the develop branch.

**Comment by KarlPurk** [comment]
Thanks @tdbrian.
