### ISSUE TITLE
Using multiple stores?

### ISSUE THREAD

**Issue by gaiottino** [KarlPurk/redux-decorators#5]
Hi,

I'm really liking the idea of these decorators. But I'm curious it it would be possible to use multiple stores? I.e. in a larger app, one to hold the state for say the breadcrumbs, and another to hold the state of the page itself. How could I go about achieving this?

Thanks

**Comment by spicywhitefish** [comment]
From [the redux docs](https://rackt.org/redux/docs/basics/Store.html):
> It’s important to note that you’ll only have a single store in a Redux application. When you want to split your data handling logic, you’ll use reducer composition instead of many stores.

Redux's imposed restriction of a single store is one of the key differences between it and Flux.

**Comment by KarlPurk** [comment]
Multiple stores aren't supported due to the single store restriction mentioned above.
