### ISSUE TITLE
Are all Reducer registered globally?

### ISSUE THREAD

**Issue by kayue** [KarlPurk/redux-decorators#7]
May I know is Action / Reducer are always registered globally?

In the [Plnkr example]( http://plnkr.co/edit/mhZNwlkrpo7k4rzEQaOr?p=preview), `app/action-reducers.ts` registered some actions. If I have a large application, looks like I have to be careful with naming my action name, make sure there is no duplication.

**Comment by KarlPurk** [comment]
Yes, you do have to be careful not to create reducers that share a name.  

You can define reducers in multiple classes though, like this:

```
@Reducer('add')
export class AddActionReducers {
  add(state)      { return { count: state.count + 1 } }
}

@Reducer('remove')
export class RemoveActionReducers {
  remove(state)   { return { count: state.count - 1 } }
}
```

This will help with organising your reducers for larger applications, but doesn't help with the name problem.

I'll have a think about possible solutions.  The first that comes to mind is namespacing, but I'm not sure what the syntax for that would look like yet - perhaps something like this?

```
@Reducer('product:add', 'product:remove')
export class ActionReducers {
  add(state)      { return { count: state.count + 1 } }
  remove(state)   { return { count: state.count - 1 } }
}
```

Or perhaps:

```
@Namespace('product')
@Reducer('add', 'remove')
export class ActionReducers {
  add(state)      { return { count: state.count + 1 } }
  remove(state)   { return { count: state.count - 1 } }
}
```

I'm leaning towards the latter.

**Comment by kayue** [comment]
Thanks for quick reply. I am new to Redux so cannot provide any comment on your solutions. 

Does other ng2 redux library has the same problem?

**Comment by KarlPurk** [comment]
Redux itself shares this problem.  Remember that actions are just functions registered against an identifier.  

Taking redux out of the equation, how would you typically solve this problem?  By changing the function names to be unique or "namespacing" the functions using modules/classes.  

You might find this useful: [reactjs/redux #786 examples - how to implement action type namespacing ?](https://github.com/reactjs/redux/issues/786)

**Comment by KarlPurk** [comment]
I'm assuming this issue is resolved.
