### ISSUE TITLE
Improvements to action reducers.

### ISSUE THREAD

**Issue by KarlPurk** [KarlPurk/redux-decorators#9]
I think action reducers should be passed the value that they operate on, rather than the full state tree.  So instead of:

```js
class MyReducers {
    add(state): { return { count: state.count + 1; } 
}
```

Instead we should be able to write something like this:

```js
class MyReducers {
    add(count = 0): { return count + 1; }
}
```

The question is how do we achieve this with decorators?  Do we assume that a class of action reducers all work on the same state slice, like this:

```js
@Reducer({slice: 'count', actions: ['add', 'remove']})
class MyReducers {
    add(count = 0): { return count + 1; }
}
```

Or do we implement this on a per-method basis, like this:

```js
class MyReducers {
    @Reducer('count') add(count = 0): { return count + 1; }
}
```

Thoughts?

**Comment by brian3kb** [comment]
To me, defining the slice and actions in a decorator on the class looks cleaner, and would scale better from a code re-readable standpoint. 
Peppering the methods within the class with decorators referencing different slices will get messy fast.

**Comment by KarlPurk** [comment]
yeh I agree with that, it’s also common to group actions that work on the same slice, so this naturally fits that pattern

**Comment by brian3kb** [comment]
Would it be feasible to make the slice an optional config on the reducer decorator? So if you don't pass a value, you just get the whole state tree?

**Comment by KarlPurk** [comment]
That would be easy enough to implement, we’ve already got it passing the whole tree

**Comment by brian3kb** [comment]
That way, for the rare few times when you do need to bounce about the state tree in a single class, you can do. And you get the option to refactor later to tidy it up into slices when things are coming together.

**Comment by KarlPurk** [comment]
Came up with a few more ideas for how this could work:

Specifying a slice:

```js
@Reducer('count', ['add'])
class MyReducers {
    add(count = 0): { return count + 1; }
}
```

Passing the whole state tree:

```js
@Reducer(['add'])
class MyReducers {
    add(state): { return { count: state + 1 }; }
}
```

Or an alternative approach could use a new decorator:

```js
@Slice('count')
@Reducer('add')
class MyReducers {
    add(count = 0): { return count + 1; }
}
```

**Comment by KarlPurk** [comment]
I went and refactored redux decorators to support the @Slice() decorator.  I also had to refactor the @InitialStore decorator to finish this functionality off.  It’s very flexible now but it’s impacted on the readability :(  I need to rethink the decorators and make some changes at some point.

We can now achieve slice-specific action reducers like this:

```js
@Slice('count') // these reducers work on the count slice of the state tree
@InitialState(0) // the count slice is initlaized with a value of 0
@Reducers('add', 'remove')
class ActionReducers {
  add(count) { return count + 1; }
  remove(count) { return count - 1; }
}
```

**Comment by KarlPurk** [comment]
I was thinking that `@Slice` could accept a second argument which is the initial state value for that slice - there's really no reason to have these 2 as separate decorators.

**Comment by KarlPurk** [comment]
`@Slice` has been implemented to match the above.  This is change is currently on the `develop` branch.
